#Base image
FROM node:20 AS builder

# Sets workdir inside container
WORKDIR /app

#Copies project dependencies
COPY package*.json

#Install project dependencies
RUN npm install

#Copies all the package
COPY . .

#Builds package(build/ or dist/)
RUN npm build

#A webserver to serve static file
FROM nginx:alpine

#copy files to nginx
COPY --from=builder /app/build /usr/share/nginx/html

#copy nginx conf
COPY nginx.conf /etc/nginx/nginx.conf
