version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: flask_app
    ports:
      - "5000:5000"
    networks:
      - vote-net

  result:
    build: ./results
    container_name: result
    ports:
      - "80:80"
    depends_on:
      - frontend
    networks:
      - vote-net
networks:
 vote-net: